services:
  dbeaver:
    image: dbeaver/cloudbeaver:24.3.0
    restart: unless-stopped
    ports:
      - "8978:8978"
    environment:
      CB_SERVER_NAME: "Local MySQL"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver_data:
